// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Modo antigo de se fazer, movido para os arquivos especificos, graph/model/category
// type Category struct {
// 	ID          string    `json:"id"`
// 	Name        string    `json:"name"`
// 	Description *string   `json:"description,omitempty"`
// 	Courses     []*Course `json:"courses"`
// }

// Modo antigo de se fazer, movido para os arquivos especificos, graph/model/course
// type Course struct {
// 	ID          string    `json:"id"`
// 	Name        string    `json:"name"`
// 	Description *string   `json:"description,omitempty"`
// 	Categories  *Category `json:"categories"`
// }

type Mutation struct {
}

type NewCategory struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type NewCourse struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	CategoryID  string  `json:"categoryId"`
}

type Query struct {
}
